blank_issues_enabled: false
contact_links:
  - name: âœ¨ Feature Request or Idea
    url: https://github.com/dennispayne/RNode_Firmware/issues/new?labels=request
    about: Request a new idea or feature
  - name: ðŸ’¬ Questions, Help & Discussion
    about: Ask anything, or get help
    url: https://github.com/markqvist/Reticulum/discussions/new/choose
  - name: ðŸ“– Read the Reticulum Manual
    url: https://markqvist.github.io/Reticulum/manual/
    about: The complete documentation for Reticulum
